name: GitHub Actions Demo
on: [push]
jobs:
    example-actions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: echo "Domino nie!!!"
            - run: docker --version
            - run: python3 --version
            - run: pylint app.py
            - run: docker build --tag test-flask-app .

