name: GitHub Actions Demo
on: [push]
jobs:
    show-versions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Check Docker version
              run: docker --version
            - name: Check Python version
              run: python3 --version
    test-code-by-pylint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-python@v1
              with:
                python-version: 3.8
            - name: Install pylint
              run: |
                python -m pip install --upgrade pip
                pip install pylint
            - name: Test code
              run: pylint app.py
    build-image:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build image
              run: docker build --tag test-flask-app .

