name: GitHub Actions Demo
on: [push]
jobs:
    Example-actions:
        runs-on: ubuntu-10
        steps:
            - docker --version
            - python3 --version
            - pylint app.py
            - docker build --tag test-flask-app .

